---
abstract: 'Easily dump variables with names'
author:
  - 'Rolf Michael Langsdorf (lanx@cpan.org)'
build_requires:
  CPAN::Meta::YAML: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
license: perl_5
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Data-Dumper-Lazy
provides:
  Data::Dumper::Lazy:
    file: lib/Data/Dumper/Lazy.pm
    version: '0.01'
requires:
	Test::Simple: '0.44'
	Test::More: '0'
  B::Deparse: '0'
	Data::Dumper: '0'
resources:
  bugtracker: http://github.com/LanX/Data-Dumper-Lazy/issues
  homepage: http://github.com/LanX/Data-Dumper-Lazy
  repository: http://github.com/LanX/Data-Dumper-Lazy.git
version: '0.01'
